<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-10-02">

<title>STAT 201: Intro. to Statistics and Data Science - Conditional probability</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">STAT 201: Intro. to Statistics and Data Science</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html">
 <span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://openintro-ims.netlify.app/"><i class="bi bi-book-half" role="img">
</i> 
 <span class="menu-text">Textbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://middlebury.instructure.com/"><i class="bi bi-bar-chart-fill" role="img">
</i> 
 <span class="menu-text">Canvas</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Conditional probability</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 2, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="housekeeping" class="level1">
<h1>Housekeeping</h1>
</section>
<section id="three-types-of-probability" class="level1">
<h1>Three types of probability</h1>
<section id="probabilities-with-contingency-tables" class="level2">
<h2 class="anchored" data-anchor-id="probabilities-with-contingency-tables">Probabilities with contingency tables</h2>
<ul>
<li><p>As we saw in the previous class, sometimes the probabilities of events are quite clear to calculate (e.g.&nbsp;dice rolls or drawing cards)</p></li>
<li><p>But oftentimes we have to use data to try and estimate probabilities (e.g.&nbsp;the Pew Research survey)</p></li>
<li><p>When we have two (or more) variables, we often want to understand the relationships between them</p></li>
</ul>
</section>
<section id="practice" class="level2">
<h2 class="anchored" data-anchor-id="practice">Practice</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/08-coffee.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Source: <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5788283/" class="uri">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5788283/</a></p>
<div class="fragment">
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Did not die</th>
<th>Died</th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Does not drink coffee</strong></td>
<td>5438</td>
<td>1039</td>
<td>6477</td>
</tr>
<tr class="even">
<td><strong>Drinks coffee occasionally</strong></td>
<td>29712</td>
<td>4440</td>
<td>34152</td>
</tr>
<tr class="odd">
<td><strong>Drinks coffee regularly</strong></td>
<td>24934</td>
<td>3601</td>
<td>28535</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>60084</td>
<td>9080</td>
<td>69164</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="discuss">
<p>Define events <span class="math inline">\(A\)</span> = died and <span class="math inline">\(B\)</span> = non-coffee drinker. Calculate the following for a randomly selected person in the cohort:</p>
<ul>
<li><p><span class="math inline">\(\text{P}(A)\)</span></p></li>
<li><p><span class="math inline">\(\text{P}(A \cap B)\)</span></p></li>
<li><p><span class="math inline">\(\text{P}(A \cup B^c)\)</span></p></li>
</ul>
</div>
</div>
</section>
<section id="marginal-and-joint-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="marginal-and-joint-probabilities">Marginal and joint probabilities</h2>
<ol type="1">
<li><p><span class="math inline">\(\text{P}(A)\)</span> is an example of a <strong>marginal probability</strong>, which is a probability involving a single random process</p>
<ul>
<li>From the contingency table, we use row totals or column totals and the overall total to obtain marginal probabilities</li>
</ul></li>
<li><p><span class="math inline">\(\text{P}(A \cap B)\)</span> and <span class="math inline">\(\text{P}(A \cup B^c)\)</span> are examples of a <strong>joint probability</strong>, which is a probability of events for two or more random variables or processes</p>
<ul>
<li>From the contingency table, we use specific cells and the overall total to obtain marginal probabilities</li>
</ul></li>
</ol>
</section>
<section id="marginal-from-joint" class="level2">
<h2 class="anchored" data-anchor-id="marginal-from-joint">Marginal from joint</h2>
<p>In simple cases, we can obtain the marginal distribution from joint distributions. You already did this!</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Did not die</th>
<th>Died</th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Does not drink coffee</strong></td>
<td>5438</td>
<td>1039</td>
<td>6477</td>
</tr>
<tr class="even">
<td><strong>Drinks coffee occasionally</strong></td>
<td>29712</td>
<td>4440</td>
<td>34152</td>
</tr>
<tr class="odd">
<td><strong>Drinks coffee regularly</strong></td>
<td>24934</td>
<td>3601</td>
<td>28535</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>60084</td>
<td>9080</td>
<td>69164</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><span class="math display">\[\begin{align*}
\text{P}(B) =\text{P}(\text{does not drink coffee}) &amp;= P(\text{does not drink coffee} \ \cap \text{ did not die}) + \\
&amp;\quad \text{P}(\text{does not drink coffee} \ \cap \text{ died}) \\
&amp;= \text{P}(B \cap A) + \text{P}(B \cap A^c) \\
&amp;= \frac{5438}{69164 } + \frac{1039}{69164} \\
&amp;= 0.0936
\end{align*}
\]</span></p>
</div>
</section>
<section id="conditional-probability" class="level2">
<h2 class="anchored" data-anchor-id="conditional-probability">Conditional probability</h2>
<ol start="3" type="1">
<li>The probability that an event will occur <em>given</em> that another event has already occurred is a <strong>conditional probability</strong>.
<ul>
<li>E.g. Given that it rained yesterday, what is the probability that it will rain today?</li>
<li>It is called “conditional” because we calculate a probability under a specific condition
<ul>
<li>Nnot to be confused with the coding <code>|</code> which is “or”</li>
</ul></li>
</ul></li>
</ol>
<ul>
<li>We can easily obtain conditional probabilities from contingency tables!</li>
</ul>
</section>
<section id="conditional-probability-with-contingency-tables" class="level2">
<h2 class="anchored" data-anchor-id="conditional-probability-with-contingency-tables">Conditional probability with contingency tables</h2>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Did not die</th>
<th>Died</th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Does not drink coffee</strong></td>
<td>5438</td>
<td>1039</td>
<td>6477</td>
</tr>
<tr class="even">
<td><strong>Drinks coffee occasionally</strong></td>
<td>29712</td>
<td>4440</td>
<td>34152</td>
</tr>
<tr class="odd">
<td><strong>Drinks coffee regularly</strong></td>
<td>24934</td>
<td>3601</td>
<td>28535</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>60084</td>
<td>9080</td>
<td>69164</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="discuss">
<p>Recall events <span class="math inline">\(A\)</span> = died and <span class="math inline">\(B\)</span> = non-coffee drinker. Write <span class="math inline">\(\text{P}()\)</span> notation for conditional probability of dying given that someone does not drink coffee, and then obtain this probability.</p>
</div>
</div>
</section>
<section id="general-multiplication-rule" class="level2">
<h2 class="anchored" data-anchor-id="general-multiplication-rule">General multiplication rule</h2>
<p>Conditional, joint, and marginal probabilities are related via the <strong>general multiplication rule</strong>*:</p>
<div class="fragment">
<p><span class="math display">\[
\text{P}(A \cap B) =
\]</span></p>
</div>
<ul>
<li><p>Very useful for finding probability that two events will happen.</p>
<ul>
<li>Example: A box has three tickets, colored red, orange, yellow. We will draw two tickets randomly without replacement. What is the probability of drawing the red ticket first and then the orange ticket?</li>
</ul></li>
</ul>
</section>
<section id="independence-and-conditional-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="independence-and-conditional-probabilities">Independence and conditional probabilities</h2>
<ul>
<li><p>Recall, events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent when what is true about their joint probability?</p></li>
<li><p>Using the general multiplication rule, what is another way to determine if events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent?</p>
<ul>
<li>Why does this make sense “intuitively”?</li>
</ul></li>
<li><div class="discuss">
<p>Using this new test of independence, are dying and abstaining from coffee independent events?</p>
</div></li>
</ul>
</section>
<section id="conditional-probability-formula" class="level2">
<h2 class="anchored" data-anchor-id="conditional-probability-formula">Conditional probability formula</h2>
<p>We can re-arrange the general multiplication formula to obtain the following general formula for conditional probability. For any events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>:</p>
<div class="fragment">
<p><span class="math display">\[
\text{P}(A| B) = \frac{\text{P}(A \cap B)}{\text{P}(B)}
\]</span></p>
</div>
<ul>
<li><div class="discuss">
<p>Recall <span class="math inline">\(A\)</span> is the event that someone died, and <span class="math inline">\(B\)</span> the event that someone does not drink coffee.</p>
<ul>
<li>Use the above formula to obtain <span class="math inline">\(\text{P}(A|B)\)</span></li>
<li>Come up with a formula for <span class="math inline">\(\text{P}(B|A)\)</span> and calculate this conditional probability for the problem at hand.</li>
</ul>
</div></li>
<li><div style="color: maroon">
<p>Note: complement rule holds for conditional probabilities if we condition on the <em>same</em> information: <span class="math inline">\(\text{P}(A|B) = 1 - \text{P}(A^c | B)\)</span></p>
</div></li>
</ul>
</section>
<section id="tree-diagram" class="level2">
<h2 class="anchored" data-anchor-id="tree-diagram">Tree diagram</h2>
<p>Tool to organize outcomes and probabilities around the structure of the data. Useful when outcomes occur sequentially, and outcomes are conditioned on predecessors. Let’s do an example:</p>
<ul>
<li><p>A class has a midterm and a final exams. 13% of students earned an A on the midterm. Of those students who earned an A on the midterm, 47% received and A on the final. Of those student who earned below an A on the midterm, 11% received an A on the final. You randomly pick up a final exam and notice the student received an A. What is the probability that they earned an A on the midterm?</p></li>
<li><div class="discuss">
<p>Using <span class="math inline">\(\text{P}()\)</span> notation, what probability are we interested in? What probabilities do we need to calculate the desired probability?</p>
</div></li>
<li><p>Let’s construct our tree!</p></li>
<li><div class="discuss">
<p>In the diagram tree, where are the three types of probabilities appearing?</p>
</div></li>
</ul>
</section>
</section>
<section id="bayes-rule" class="level1">
<h1>Bayes’ Rule</h1>
<section id="bayes-rule-1" class="level2">
<h2 class="anchored" data-anchor-id="bayes-rule-1">Bayes’ Rule</h2>
<ul>
<li><p>As we saw before, the two conditional probabilities <span class="math inline">\(P(A|B)\)</span> and <span class="math inline">\(P(B|A)\)</span> are not the same. But are they related in some way?</p></li>
<li><p><strong>Bayes’ rule</strong>:</p></li>
</ul>
<div class="fragment">
<p><span class="math display">\[
P(A|B) =
\]</span></p>
</div>
<ul>
<li>Can we go even further?</li>
</ul>
<div class="fragment">
<p><span class="math display">\[
P(A|B) =
\]</span></p>
</div>
<ul>
<li>Why is this seemingly more complicated formula useful?</li>
</ul>
</section>
<section id="bayes-theorem-more-general" class="level2">
<h2 class="anchored" data-anchor-id="bayes-theorem-more-general">Bayes’ Theorem (more general)</h2>
<ul>
<li><p>Suppose we have a random process and have a defined event <span class="math inline">\(B\)</span></p></li>
<li><p>Further suppose we can break up the sample space into <span class="math inline">\(k\)</span> disjoint/mutually exclusive outcomes or events <span class="math inline">\(A_{1}, A_{2}, \ldots, A_{k}\)</span></p>
<ul>
<li>The <span class="math inline">\(A_{i}\)</span> may or may not intersect with <span class="math inline">\(B\)</span></li>
</ul></li>
<li><p>Without loss of generality, suppose we want <span class="math inline">\(\text{P}(A_{1} | B)\)</span></p></li>
<li><p><strong>Bayes’ Theorem</strong> states:</p>
<p><span class="math display">\[\begin{align*}
\text{P}(A_{1} |  B ) &amp;= \frac{\text{P}(A_{1} \cap B)}{\text{P}(B)}\\
&amp;= \frac{\text{P}(B|A_{1})\text{P}(A_{1})}{\text{P}(B\cap A_{1}) + \text{P}(B \cap A_{2}) + \ldots + \text{P}(B \cap A_{k})} \\
&amp;=\frac{\text{P}(B|A_{1}) \text{P}(A_{1})}{\text{P}(B|A_{1}) \text{P}(A_{1}) + \text{P}(B | A_{2}) \text{P}(A_{2}) + \ldots + \text{P}(B | A_{k} ) \text{P}(A_{k})}
\end{align*}\]</span></p></li>
</ul>
<div class="notes">
<p>Blob picture. How would this change if we wanted <span class="math inline">\(P(A_{2} | B)\)</span> instead?</p>
</div>
</section>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<ul>
<li><p>In Canada, about 0.35% of women over 40 will develop breast cancer in any given year. A common screening test for cancer is the mammogram, but this test is not perfect.</p></li>
<li><p>In about 11% of patients with breast cancer, the test gives a <em>false negative</em>: it indicates a woman does not have breast cancer when she does have breast cancer.</p></li>
<li><p>In about 7% of patients who do not have breast cancer, the test gives a <em>false positive</em>: it indicates these patients have breast cancer when they actually do not.</p></li>
<li><p>If we tested a random Canadian woman over 40 for breast cancer using a mammogram and the test came back positive, what is the probability that the patient actually has breast cancer?</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>