---
title: "Midterms"
---

## Midterm 2 {#midterm1}

### Logistics

-   **When and where**: Wednesday, Nov. 20 *and* Thursday, Nov. 21 during class (75 minutes each)

    -   Wednesday will be the written portion

    -   Thursday will be coding-focused (i.e. the majority of questions will require you to use `R` in some way)

        -   A starter `.Rmd` template will be made available via the Canvas assignment associated with the midterm.

        -   Be sure to type your name in the Honor Code statement provided at the top of the document

        -   You will be required to submit **both** the completed `.Rmd` and the knitted output to Canvas by the end of the allotted time. Be sure to budget this time in appropriately.

    -   **Important**: Prof. Tang will be proctoring the exam. On Thursday, you can expect Prof. Tang to walk around the room several times in order discourage the temptation of using Google/ChatGPT/other AI tools

-   **What**: focusing on content from Week 5 through the beginning of Week 10 (i.e. all inference topics, Normal distribution, and SLR)

    -   Lightly cumulative (but no probability problems like those on Midterm 1)

    -   Feel comfortable making plots and wrangling data

### What to bring

-   **For Wednesday: you can bring a single-sided 8.5"x11" formula sheet.** This sheet should include formulas only! No worked out examples, pictures, descriptions, or definitions are allowed. You will be asked to submit the formula sheet alongside the midterm on Wednesday. The formula sheet will be returned to you for your midterm on Thursday, so be sure to write your name on your sheet.

-   **For Thursday**: during the coding component of the midterm, you are welcome to use/access your own code and any code posted on the course website. Aside from accessing the course website, the midterm is *not* open internet. Once again, use of Google/ChatGPT/other AI Tools during the midterm is strictly forbidden and would be in violation of the Honor Code.

-   ::: {style="color: maroon"}
    You should bring a calculator to day 1 of the midterm. If you do not have one, the department can provide very basic calculators.
    :::

-   You will be provided the following two tables alongside your exam: a table of [z-score probabilities](z_table.pdf) and table of [$t$-distribution percentiles](t_table.pdf). We will go over how to read them in class, but make sure you feel comfortable with them before the midterm!

-   ::: {style="color: maroon"}
    You should bring a fully charged laptop to day 2 of the midterm.
    :::

### Preparation

-   The best preparation you can do for the midterm is to go back through your notes and homework and be honest with yourself about what you do/don't understand. This means going through the painful process of looking at feedback on Canvas. For the concepts that you need to practice more, try more problems (see below)!

-   Try answering some of the comprehension questions at the end of the slides. You should expect some questions on the midterm that assess your "big picture" understanding of the material.

-   As you're studying, try making a rough draft of your formula sheet. Then use that formula sheet (rather than your notes) when attempting new practice problems. This will more accurately simulate the test-taking experience.

    -   Based on your experiences and practice, you should make a new version of the formula sheet. Keep iterating until you've found one that works for you.
    -   Practice the problems using the provided tables of z-score probabilities and t-distribution percentiles.

-   For coding, go back through your old `.Rmd`s and make sure you understand everything that is happening! You might also consider re-doing a coding problem without looking at your previous code.

-   More practice problems. These problems are representative of what you can expect on the midterm:

    -   [Practice problems involving coding](practice_probs/practice-midterm2-coding.qmd)

    -   [Practice problems written](midterm2_review_probs.pdf)

------------------------------------------------------------------------

## Midterm 1

### Logistics

-   **When and where**: Thursday, October 10 during class (75 minutes)

-   **What**: content through end of Week 4 (i.e. through Simpson's Paradox)

    -   You will not be asked to write code, but you may be asked to read or critique it

-   **Important**: Prof. Tang will be proctoring the exam

-   You will not have a problem set assigned this week!

-   Prof. Tang will move Friday's office hours to Wednesday 10/09 3-4pm instead.

-   ::: {style="color: maroon"}
    You should bring a calculator to the midterm. If you do not have one, the department can provide very basic calculators.
    :::

## Preparation

-   The best preparation you can do for the midterm is to go back through your notes and homework and be honest with yourself about what you do/don't understand. This means going through the painful process of looking at feedback on Canvas. For the concepts that you need to practice more, try more problems (see below)!

-   Another way to prepare is to create your own study guide with summaries and examples of important concepts. As you study, it would be a good idea to compile a list of questions that you might have.

-   Work on the practice problems that were distributed at the end of classes but not assigned.

-   For extra practice, additional review problems will soon be made available below. These questions are not necessarily representative of the typical scope and difficulty of individual exam questions. This review is not comprehensive, nor does it represent the expected amount of time for it will take for you to complete the midterm.

    -   [Extra problems here](midterm1_review_probs.pdf) and [here](midterm1_review_extra.pdf)
    -   [Video](https://drive.explaineverything.com/thecode/NXHHJJN) recap of probability
