---
title: "Schedule"
page-layout: full
format: 
  html:
    css: styles.css
---

Jump to:

-   [Week 1](#week1)
-   [Week 2](#week2)
-   [Week 3](#week3)
-   [Week 4](#week4)
-   [Week 5](#week5)
-   [Week 6](#week6)
-   [Week 7](#week7)
-   [Week 8](#week8)
-   [Week 9](#week9)
-   [Week 10](#week10)
-   [Week 11](#week11)
-   [Week 12](#week12)

+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| Week                               | Date     | In-class material                                                                                                                                                                              | Coding practice                                                                                                                                       | Assignments                                                                                    |
+:==================================:+==========+================================================================================================================================================================================================+=======================================================================================================================================================+================================================================================================+
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week1}                       | M 09/09  | -   Topic: [Welcome!](slides/slides-00-welcome.qmd) (pdf [here](slides/pdf/slides-00.pdf))                                                                                                     |                                                                                                                                                       | -   Bring your completed quiz to next class                                                    |
| **1**                              |          |     -   Directions for printing at bottom                                                                                                                                                      |                                                                                                                                                       |                                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       | -   Fill out [this survey](https://forms.gle/GmbiQXXCEk7xejJt5) by next class.                 |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 09/11  | -   Topic: [Study design](slides/slides-01-study-design.qmd) (pdf [here](slides/pdf/slides-01.pdf))                                                                                            |                                                                                                                                                       | -   Wednesday problems on [Problem Set 1](homework/hw1.pdf)                                    |
|                                    |          |     -   [Practice problems](practice_probs/practice-01-study-design.qmd)                                                                                                                       |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 09/12  | -   Topic: [Software installation](slides/slides-02-toolkit-installation.qmd) (no need to print slides!)                                                                                       | -   Intro to R and R Markdown                                                                                                                         | -   Thursday problems on [Problem Set 1](homework/hw1.pdf)                                     |
|                                    |          | -   `R` and `.Rmd` [basics](live_code/intro_R.qmd)                                                                                                                                             |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   Download the following .Rmd template and drag to your new STAT 201 folder: {{< downloadthis live_code/template_intro_R.Rmd dname="intro_R" label="Rmd template" id=mtcars-btn >}}      |     {{< downloadthis coding_practice/coding-practice-02-intro-r.Rmd dname="coding-practice-intro-R" label="Coding practice" id=mtcars-btn >}}         |                                                                                                |
|                                    |          |     -   Recording [here](https://middlebury.zoom.us/rec/share/_fy_lpsyDzdPIUmfu7k8FA1NksnClGkSHz0cPTV5ZXuc39LywW9h5oXchUXWaqhi.x6RNwGidelNURP9U%20Passcode:%203g%5ESS69r)! Password: 3g\^SS69r |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week2}                       |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **2**                              | M 09/16  | -   Topic: [Numerical data (part 1)](slides/slides-03-numerical-pt1.qmd) (pdf [here](slides/pdf/slides-03.pdf))                                                                                |                                                                                                                                                       | -   Monday problems on [Problem Set 2](homework/hw2.pdf)                                       |
|                                    |          |     -   [Live code](live_code/numerical_pt1_live.qmd) and associated template: {{< downloadthis live_code/stat201_live_code.Rmd dname="stat201_live_code" label="Rmd" id=mtcars-btn >}}        |                                                                                                                                                       | -   [Sunflower field](homework/sunflower_field.pdf)                                            |
|                                    |          |     -   [Practice problems](practice_probs/practice-03-numerical-data-pt1.qmd)                                                                                                                 |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 09/18  | -   Topic: [Numerical data (part 2)](slides/slides-04-numerical-pt2.qmd) (pdf [here](slides/pdf/slides-04.pdf))                                                                                | -   Basic plots and summary statistics in R                                                                                                           | -   Wednesday problems on [Problem Set 2](homework/hw2.pdf)                                    |
|                                    |          |     -   [Live code](live_code/numerical_pt2_live.qmd)                                                                                                                                          |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Practice problems](practice_probs/practice-04-numerical-data-pt2.qmd)                                                                                                                 |     {{< downloadthis coding_practice/coding-practice-04-numerical-pt2.Rmd dname="coding-practice-numerical" label="Coding practice" id=mtcars-btn >}} |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 09/19  | -   Topic: [ggplot for numerical variables](slides/slides-05-numerical-data-viz.qmd) (pdf [here](slides/pdf/slides-05.pdf))                                                                    | -   Introduction to ggplot                                                                                                                            | -   Thursday problems on [Problem Set 2](homework/hw2.pdf)                                     |
|                                    |          |     -   Live code                                                                                                                                                                              |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |     {{< downloadthis coding_practice/coding-practice-05-ggplot.Rmd dname="coding-practice-ggplot" label="Coding practice" id=mtcars-btn >}}           | -   Associated `R` problems                                                                    |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |     {{< downloadthis homework/hw2_r.Rmd dname="hw2_r" label="Problem Set 2" id=mtcars-btn >}}  |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week3}                       |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **3**                              | M 09/23  | -   Topic: [categorical data](slides/slides-06-categorical-data.qmd) (pdf [here](slides/pdf/slides-06.pdf))                                                                                    | -   Visualizing categorical data                                                                                                                      | -   Monday problems on [Problem Set 3](homework/hw3.pdf)                                       |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |     {{< downloadthis coding_practice/coding-practice-06-categorical.Rmd dname="coding-practice-categorical" label="Coding practice" id=mtcars-btn >}} |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 09/25  | -   Topic: [Introduction to data wrangling](slides/slides-07-wrangling.qmd) (pdf [here](slides/pdf/slides-07.pdf))                                                                             | -   Practice with wrangling                                                                                                                           | Begin working through [this `R` lab](homework/hw3_r.Rmd):                                      |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Live code](live_code/data_wrangling_pt1.qmd) example                                                                                                                                  |     {{< downloadthis coding_practice/coding-practice-07-wrangling.Rmd dname="coding-practice-wrangling" label="Coding practice" id=mtcars-btn >}}     | {{< downloadthis homework/hw3_r.Rmd dname="hw3_r" label="Problem Set 3" id=mtcars-btn >}}      |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 09/26  | -   Topic: Data wrangling (cont.)                                                                                                                                                              |                                                                                                                                                       | Continue working on the above lab.                                                             |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Live code](live_code/data_wrangling_pt2.qmd) example                                                                                                                                  |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Group exercise](live_code/kaggle_survey_analysis.Rmd)                                                                                                                                     |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     {{< downloadthis live_code/kaggle_survey_analysis.Rmd dname="kaggle_survey_analysis" label=".Rmd" id=mtcars-btn >}}                                                                        |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week4}                       |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **4**                              | M 09/30  | Topic: [Probability basics](slides/slides-08-probability.qmd) (pdf [here](slides/pdf/slides-08.pdf))                                                                                           |                                                                                                                                                       | -   Monday problems on [Problem Set 4](homework/hw4.pdf)                                       |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   Introduce [Midterm 1](midterms.qmd)                                                                                                                                                        |                                                                                                                                                       | **Note**: this week's problem set is due Saturday 10/05 midnight!                              |
|                                    |          | -   [Practice problems](practice_probs/practice-08-probability.qmd)                                                                                                                            |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 10/02  | Topic: [Conditional probability](slides/slides-09-conditional-probability.qmd) (pdf [here](slides/pdf/slides-09.pdf))                                                                          |                                                                                                                                                       | -   Wednesday problems on [Problem Set 4](homework/hw4.pdf)                                    |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Practice problems](practice_probs/practice-09-conditional-probability.qmd)                                                                                                                |                                                                                                                                                       | **Note**: this week's problem set is due Saturday 10/05 midnight!                              |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 10/03  | Topic: [Simpson's paradox](slides/slides-10-simpsons.qmd) (pdf [here](slides/pdf/slides-10.pdf))                                                                                               | -   Practice with wrangling: probabilities                                                                                                            |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |     {{< downloadthis coding_practice/coding-practice-10-simpsons.Rmd dname="coding-practice-probability" label="Coding practice" id=mtcars-btn >}}    |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week5}                       |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **5**                              | M 10/07  | Topic: [Introduction to Bootstrap](slides/slides-11-bootstrap.qmd) (pdf [here](slides/pdf/slides-11.pdf))                                                                                      |                                                                                                                                                       | No problem set this week. Study for midterm!                                                   |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Live code](live_code/bootstrap_dist.qmd)                                                                                                                                                  |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 10/09  | Topic: [Bootstrap confidence intervals](slides/slides-12-bootstrap_ci.qmd) (pdf [here](slides/pdf/slides-12.pdf))                                                                              | -   Bootstrap CIs (**due Monday midnight**)                                                                                                           |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   Please complete this [mid-semester survey](https://forms.gle/LhX7EQaduKLXDEzm8)                                                                                                            |     {{< downloadthis coding_practice/coding-practice-12-bootstrap.Rmd dname="coding-practice-bootstrap-ci" label="Coding practice" id=mtcars-btn >}}  |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 10/10  | Midterm 1!                                                                                                                                                                                     |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week6}                       |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **6**                              | M 10/14  | -   Topic: [Introduction to Hypothesis Testing (HT) with simulation](slides/slides-13-intro-testing.qmd) (pdf [here](slides/pdf/slides-13.pdf))                                                | -   Bootstrap CIs from last Thursday due tonight                                                                                                      | -   Monday problems in [Problem Set 5](homework/hw5.pdf)                                       |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Practice problems](practice_probs/practice-13-intro_testing.qmd)                                                                                                                      |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 10/16  | -   Topic: [HTs with randomization](slides/slides-14-randomization.qmd) (pdf [here](slides/pdf/slides-14.pdf))                                                                                 |                                                                                                                                                       | -   Get started on problems 1-3 in the `.Rmd` problems.                                        |
|                                    |          |     -   [Live code](live_code/intro_testing.qmd) for HT for one proportion                                                                                                                     |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |     {{< downloadthis homework/hw5_r.Rmd dname="hw5_r" label="Problem Set 5" id=mtcars-btn >}}  |
|                                    |          |     -   [Live code](live_code/randomization_two_props.qmd) for HT for difference in proportions                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Practice problems](practice_probs/practice-14-randomization.qmd)                                                                                                                      |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 10/18  | -   Topic: [HTs with bootstrapping](slides/slides-15-single-mean.qmd) (pdf [here](slides/pdf/slides-15.pdf))                                                                                   |                                                                                                                                                       | -   Continue working on [Problem Set 5](homework/hw5.pdf)                                      |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Practice problems](practice_probs/practice-15-ht-basics.qmd) (CI and HT concepts)                                                                                                     |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week7}                       |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **7**                              | M 10/21  | Topic: Normal distribution ([worksheet](slides/worksheet-16-normal.qmd))                                                                                                                       |                                                                                                                                                       | -   Monday problems in [Problem Set 6](homework/hw6.pdf)                                       |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Practice problems](practice_probs/practice-16-normal.qmd) (some in worksheet)                                                                                                             |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 10/23  | Topic: [Central Limit Theorem + CIs with mathematical models](slides/slides-17-clt.qmd) (pdf [here](slides/pdf/slides-17.pdf))                                                                 |                                                                                                                                                       | -   Wednesday problems in [Problem Set 6](homework/hw6.pdf)                                    |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Practice problems](practice_probs/practice-17-clt.qmd)                                                                                                                                    |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 10/24  | Topic: [CIs for means using CLT](slides/slides-18-ci-mean.qmd) (pdf [here](slides/pdf/slides-18.pdf))                                                                                          |                                                                                                                                                       | -   Thursday problems in [Problem Set 6](homework/hw6.pdf)                                     |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Live code](live_code/ci_diff_means.qmd)                                                                                                                                                   |                                                                                                                                                       | -                                                                                              |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |     {{< downloadthis homework/hw6_r.Rmd dname="hw6_r" label="Problem Set 6" id=mtcars-btn >}}  |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week8}                       |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **8**                              | M 10/28  | Topic: Introduce final project, [HTs with mathematical models](slides/slides-19-ht-prop.qmd) (pdf [here](slides/pdf/slides-19.pdf))                                                            |                                                                                                                                                       | -   Monday problems in [Problem Set 7](homework/hw7.pdf)                                       |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       | -   Final project groups!                                                                      |
|                                    |          | -   [Practice problems](practice_probs/practice-19-ht-prop.qmd)                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 10/30  | Topic: [HTs (cont.)](slides/slides-20-ht-cont.qmd) (diff. in proportions and single mean) (pdf [here](slides/pdf/slides-20.pdf))                                                               |                                                                                                                                                       | -   Wednesday problems in [Problem Set 7](homework/hw7.pdf)                                    |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Practice problems](practice_probs/practice-20-ht-cont.qmd)                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| So spooky!                         | R 10/31  | Topic: [HTs (cont.)](slides/slides-21-ht-diff-means.qmd) (paired difference, diff. in means) (pdf [here](slides/pdf/slides-21.pdf))                                                            |                                                                                                                                                       | -   Work on proposal for data collection (due Monday 11/4 midnight)                            |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   Section A: [live code](live_code/ht_diff_means_a.qmd)                                                                                                                                      |                                                                                                                                                       | -   Thursday problems in [Problem Set 7](homework/hw7.pdf)                                     |
|                                    |          | -   Section B: [live code](live_code/ht_diff_means_b.qmd)                                                                                                                                      |                                                                                                                                                       |                                                                                                |
|                                    |          | -   Project work day                                                                                                                                                                           |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week9}                       |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **9**                              | M 11/4   | -   Review of inference with CLT                                                                                                                                                               | -   Pivoting coding practice (due tonight midnight)                                                                                                   | -   Proposal for data collection due tonight!                                                  |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Practice problems](practice_probs/inference_review.pdf)                                                                                                                               |     {{< downloadthis coding_practice/coding-practice-22-pivoting.Rmd dname="coding-practice-pivoting" label="Coding practice" id=mtcars-btn >}}       | -   Problem set 7 due Wednesday                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Live code](live_code/pivoting.qmd) for pivoting                                                                                                                                           |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| Dessert social 3-4:30pm in WNS 101 | W 11/6   | -   Topic: [Introduction to simple linear regression](slides/slides-23-slr-intro.qmd) (pdf [here](slides/pdf/slides-23.pdf))                                                                   |                                                                                                                                                       | -   Wednesday problems in [Problem Set 8](homework/hw8.pdf) (due next Thursday)                |
|                                    |          |     -   [PDF with figures](slides/slr_figs.qmd)                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 11/7   | -   Topic: [SLR interpretation](slides/slides-24-slr-interpretation.qmd) (pdf [here](slides/pdf/slides-24.pdf))                                                                                |                                                                                                                                                       | -   Thursday problems in [Problem Set 8](homework/hw8.pdf) (due next Thursday)                 |
|                                    |          |     -   [Practice problems](practice_probs/practice-24-slr.qmd)                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week10}                      |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **10**                             | M 11/11  | -   Topic: [Inference in SLR](slides/slides-25-slr-inference.qmd) (pdf [here](slides/pdf/slides-25.pdf))                                                                                       |                                                                                                                                                       | -   Monday problems in [Problem Set 8](homework/hw8.pdf) (due Thursday)                        |
|                                    |          | -   Fitting SLR in `R`                                                                                                                                                                         |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Live code](live_code/slr1.qmd) for coding SLR in `R`                                                                                                                                  |                                                                                                                                                       | -   Note: questions 4-7 in the `.Rmd` will probably have to wait until Wednesday class. Sorry! |
|                                    |          | -   Introduce [Midterm 2](midterms.qmd)                                                                                                                                                        |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |     {{< downloadthis homework/hw8_r.Rmd dname="hw8_r" label="Problem Set 8" id=mtcars-btn >}}  |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 11/13  | -   Topic: [Simulation-based CIs for SLR](slides/slides-26-slr-bootstrap-ci.qmd) (pdf [here](slides/pdf/slides-26.pdf))                                                                        | -   Fitting SLR coding practice                                                                                                                       | -   Homework 8 due tomorrow!                                                                   |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Live code](live_code/slr_bootstrap.qmd)                                                                                                                                               |     {{< downloadthis coding_practice/coding-practice-25-slr.Rmd dname="coding-practice-slr" label="Coding practice" id=mtcars-btn >}}                 |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | -   [Live code](live_code/slr_extras.qmd) for pretty output using `broom` and factors                                                                                                          |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 11/14  | -   Topic: [Simulation-based HTs for SLR](slides/slides-27-slr-randomization.qmd) (pdf [here](slides/pdf/slides-27.pdf))                                                                       |                                                                                                                                                       | -   Homework 8 due tonight                                                                     |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     {{< downloadthis coding_practice/coding-practice-27-slr-randomization.Rmd dname="slr-randomization" label="Template" id=mtcars-btn >}}                                                     |                                                                                                                                                       | -   Start studying for Midterm 2                                                               |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |     -   [Live code](live_code/slr-ht-randomization.qmd)                                                                                                                                        |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week11}                      |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **11**                             | M 11/18  | -   Topic: [Introduction to MLR](slides/slides-28-mlr-intro.qmd) (pdf [here](slides/pdf/slides-28.pdf))                                                                                        |                                                                                                                                                       | Study for midterm                                                                              |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 11/20  | Midterm 2: Part 1                                                                                                                                                                              |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 11/21  | Midterm 2: Part 2                                                                                                                                                                              |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    |          | ::: {style="color: maroon"}                                                                                                                                                                    |                                                                                                                                                       |                                                                                                |
|                                    |          | Thanksgiving Break!                                                                                                                                                                            |                                                                                                                                                       |                                                                                                |
|                                    |          | :::                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| ::: {#week12}                      |          | **In-class material**                                                                                                                                                                          | **Coding practice**                                                                                                                                   | **Assignments**                                                                                |
| :::                                |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **12**                             | M 12/02  | [Project](slides/slides-29-project.qmd) work day!                                                                                                                                              |                                                                                                                                                       | Work on final project!                                                                         |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | `.Rmd` template for final project:                                                                                                                                                             |                                                                                                                                                       | -   Read through the [project description](project/project_description.qmd) page               |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          | {{< downloadthis project/final_project_template.Rmd dname="final_project" label="Template" id=mtcars-btn >}}                                                                                   |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | W 12/04  | Project work day!                                                                                                                                                                              |                                                                                                                                                       | -   Work on rough draft                                                                        |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       |                                                                                                |
|                                    |          |                                                                                                                                                                                                |                                                                                                                                                       | -   Midterm revisions                                                                          |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 12/05  | Project work day!                                                                                                                                                                              |                                                                                                                                                       | -   Rough draft of two sections of due Sunday 11:59pm                                          |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| **13**                             | W 12/11  | Section AZ: Project presentations 7-10pm                                                                                                                                                       |                                                                                                                                                       | Slides due by 6pm                                                                              |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | R 12/12  | Section BY: Project presentations 9am-12pm                                                                                                                                                     |                                                                                                                                                       | Slides due by 8am                                                                              |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|                                    | Su 12/15 | Report, data + dictionary, and reflection due at 11:59pm                                                                                                                                       |                                                                                                                                                       |                                                                                                |
+------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[10,10,40,40\]"}

To print PDF of the slides with multiple slides on a page:

1.  Download the PDF and open the document
2.  Print the document
    i.  In the Print options, go to *Layout* then choose your preferred number of *Pages per Sheet*
    ii. Hit *Print*
