---
title: "Probability"
author: "Practice problems"
date: "September 30, 2024"
format:
  pdf:
    keep-tex: true
    include-in-header:
      text: |
        \setkomafont{author}{\small}
        \setkomafont{date}{\small}
    geometry:
      - left=1in
      - right=1in
      - top=1in
---

```{r echo = F, message = F, warning = F}
library(tidyverse)
library(openintro)
library(knitr)
```

1.  If events $A$ and $B$ are disjoint, what is a simple formula for $P(A \cup B)$?

2.  ($^*$) The American Community Survey (ACS) is an ongoing survey that provides data every year to give communities the current information they need to plan investments and services. The 2010 ACS estimated that 14.6% of Americans live below the poverty line, 20.7% speak a language other than English (i.e. a foreign language) at home, and 4.2% fall into both categories.

    a.  Are living below the poverty line and speaking a foreign language at home disjoint?
    b.  Draw a Venn diagram summarizing the probabilities and their associated probabilities. Be sure to complete the diagram by including a \`\`bounding box".
    c.  What percent of Americans live below the poverty line and only speak English at home?
    d.  What percent of Americans live below the poverty line or speak a foreign language at home?
    e.  What percent of Americans live below the poverty line and only speak English at home?
    f.  Is the event that someone lives below the poverty line independent of the event that the person speaks a foreign language at home?

3.  In a multiple choice exam, there are 5 questions and 4 choices for each question. Nancy has not studied for the exam at all and decides to randomly guess the answers. What is the probability that:

    a.  the first question Nancy gets correct is the 5th question? State any assumptions that you make.

    b.  Nancy gets all of the questions right?

    c.  Nancy gets at least one question right?
