---
title: "Kaggle survey: group data wrangling"
author: "Your name"
date: "2024-09-26"
output: html_document
---

We will now work a larger subset of the Kaggle data science survey data!

```{r setup, message = F}
# load libraries here
library(readr)

## modify this line accordingly!
url_file <- "https://raw.githubusercontent.com/midd-stat201-fall2024/midd-stat201-fall2024.github.io/refs/heads/main/data/datascience_survey.csv"
```

## Group analysis

I want your group to generate your own investigation. Using your data-wrangling and plotting skills to do some EDA. After about a half hour, your group will share your process and results with the rest of the class!

Your final results must include:

-   A meaningful use of `group_by()`

-   Summary statistics or frequency table

-   Visualization with meaningful labels/titles

You can create more than one visualization and/or more than one table. Whatever speaks to you! The individual components (i.e. table/summary stats vs plot) do not need to use the same set of variables. Feel free to create as many code chunks as you'd like! There is a data dictionary at the bottom of this page that defines all the variables in the data set for you.

## Data dictionary

Below is the data dictionary for the subset of the Kaggle data data.

-   `Country`: home country of employee (character)
-   `Gender`: specified gender (character)
-   `Age`: age at time of survey (numeric)
-   `EmploymentStatus`: reported employed status (character)
-   `EmployerIndustry`: employer's industry (character)
-   `Major`: college major (character)
-   `CompensationAmount`: annual compensation (numeric)
-   `CompensationCurrency`: three-letter currency code (character)
-   `CurrentJobTitle`: job title (character)
-   `TitleFit`: assessment of how well the job title fits ("Fine", "Perfectly", "Poorly")
-   `LanguageRecommendation`: recommended programming language (character)
-   `DataScienceIdentity`: does the respondent identify as a data scientist (character)
-   `WorkDataVisualizations`: proportion of job dedicated to creating data visualizations, broken into pre-determined categories (character)
-   `JobSatisfaction`: rating of job satisfaction on scale of 1-10, where 1 is not satisfied and 10 is highly satisfied (character)
-   `JobSatisfaction2`: numeric version of `JobSatisfaction` (numeric)
-   `ConversionUSD`: conversion factor from `CompensationCurrency` to USD (numeric)
